### ISSUE TITLE
Cannot find DGCI: URN:UVCI:01DE/....

### ISSUE THREAD

**Issue by hsanjuan** [eu-digital-green-certificates/dgca-wallet-app-android#70]
## Describe the bug

Thank you for making an open source application that is avilable on F-Droid.

I am using version 1.0.7-tst.

When attempting to add my EU Digital Covid certificate issued in Germany I can scan the code and the application correctly reads the details. However, I get the above error when hitting "save".

## Expected behaviour

It should be able to add the certificate just fine.

Is this because of a syncing issue or something else? My certificate was issued a few hours ago.

**Comment by hsanjuan** [comment]
I forgot to say, the application requests a TAN. However, no TAN has been provided in any documents to me, so I just wrote something random.

**Comment by daniel-eder** [comment]
Germany has not implemented the tan functionality into their toolchain, please refer to https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/issues/66

**Comment by hsanjuan** [comment]
Is the fact that no TAN is needed related to the DGCI being invalid? The certificate seems to be perfectly readable. Per #66 you seem to imply that:

> I suspect the issue could be missing public keys

Has this been verified? Is there an issue to track missing public keys?

**Comment by daniel-eder** [comment]
There are no missing keys at this point, so the certificate should be detected as valid with all official apps for each member state. 

When building the verifier app from source or using a non-official build it is possible the app is not accessing the productive trustlist/public keys, as access to the trustlist is granted by the member states ( see https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 ). In that case, the publisher of the app needs to get in touch with their ministry of health to organize access.

**Comment by hsanjuan** [comment]
> There are no missing keys at this point, so the certificate should be detected as valid with all official apps for each member state.

Yes, it works with the German app. But what about this wallet app (not the verifier app)? I have tested the app-acc-release-signed-1.0.7.apk and the app-tst-release-signed-1.0.7.apk provided in the releases page and get the `Cannot find DGCI: URN:UVCI:01DE/...` when adding, even though it can read the certificate details.

What does that error mean? Is it trying to verify certificates even if it's not the verifier app? Why cannot it just store it?

This app is for storing digital EU green certificates, and I am trying to store one, and it does not work, so perhaps we can acknowledge there is a problem?

**Comment by daniel-eder** [comment]
The apps found here are only template apps to be used by the member states, not ready-to-use applications.

The apk releases are set up to work with the test (app-test) and acceptance (app-acc) environments in order to give member state developers a reference solution, but do not work with the productive environment, as wallet apps are in the sovereignty of the member states, not of the European Union/European Commission.

These template apps only work with productive certificates if a member state adjusts and configures them to work with their national backend (or provides a third party with the permission and required access to do so)

**Comment by hsanjuan** [comment]
Thank you, I understand. An update to the README outlining this information would help, since the apks are circulated on a popular F-Droid repository and there is not much information on the app needing additional configuration or how to do that.

I would have obviously not asked about a working version of this app, had I known this implied invading the sovereignty of members states. My sincere apologies for the time wasted and my best congrats to the European Commission for ensuring no national contract to develop an equivalent app goes wasted.

**Comment by daniel-eder** [comment]
That's a fair point, I added a brief statement to the readme's for the app repos (pending merge).

In all fairness I do need to point out that while the releases on here cannot be used due to not being connected to a production backend, the apps are functionally ready to use, and member states either use these apps with only minor modification (translation and branding) or copied/included the core functionality into existing covid-related apps so the work done here is generally not duplicated.
